# Generated by Django 3.2.8 on 2021-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211019_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(default='0', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Страница'),
        ),
    ]
