# Generated by Django 3.2.8 on 2021-11-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_order',
            field=models.TextField(default=1, max_length=4000, verbose_name='Список товаров'),
            preserve_default=False,
        ),
    ]
