# Generated by Django 3.2.8 on 2021-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=400, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Адресс доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='list_order',
            field=models.TextField(max_length=4000, null=True, verbose_name='Список товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.SmallIntegerField(null=True, verbose_name='Телефон'),
        ),
    ]
